### ISSUE TITLE
Wither Bones don't drop if Hephaestus (TConstruct) is installed, but Red Heart Canister recipe is hardcoded to use BHC Wither Bones

### ISSUE THREAD

**Issue by unilock** [JongWasTaken/Baubley-Heart-Canisters-Fabric#4]
BHC's Wither Bones don't drop from Wither Skeletons if "tconstruct" (a.k.a. Hephaestus on Fabric) is installed, as seen here in `DropHandler`:

https://github.com/JongWasTaken/Baubley-Heart-Canisters-Fabric/blob/e408a8931b9c9e86b36a4b9f9100d332ade9c903/src/main/java/pw/smto/bhc/common/util/DropHandler.java#L51

However, the Red Heart Canister recipe is hardcoded to use BHC's Wither Bones, instead of, say, a tag containing both BHC's Wither Bones and Hephaestus's Necrotic Bones:

https://github.com/JongWasTaken/Baubley-Heart-Canisters-Fabric/blob/e408a8931b9c9e86b36a4b9f9100d332ade9c903/src/main/resources/data/bhc/recipes/red_heart_canister.json#L8

This makes the Red Heart Canister impossible to craft with Hephaestus installed.

**Comment by JongWasTaken** [comment]
Hello, and thank you for reporting this issue. 
 
Unfortunately I don't have a working internet connection right now, and cannot push a fix because of it. 
 
If possible (and if you care enough), could you create a PR for this? Otherwise the earliest date at which I could fix this would be the 5th.

Either way, have a good day!

**Comment by JongWasTaken** [comment]
Thanks to _finally_ having internet again, I was able to build and publish 1.0.5 today.  
  
The usual Modrinth/CurseForge stuff applies, and this issue can finally be closed.  
Thanks again!
